name: example_flutter
description: An example project for flutter-desktop-embedding.

version: 0.0.4

environment:
  sdk: '>=2.6.0-dev.6.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.10.2-pre.54'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_icons: 0.3.1
  mysql1: 0.17.0+1
  path: ^1.6.4
  flushbar: 1.9.1
  virtual_keyboard: 0.1.4
  # flutter_serial_port: ^0.0.7
  ffi_libserialport:
    path: ../ffi_libserialport
  #   git:
  #     url: https://github.com/defned/ffi_libserialport.git
  #     ref: 40c358b09bca080f6d69d0f7bc50e242b7f1192d
  auto_size_text: any
  fluro: any
  logging: any
  cupertino_icons: ^0.1.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - blobs/libserialport_c-mac64.so
    - blobs/libserialport_c-win64.dll
    - lang/hu.json
    - lang/en.json

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Digit
      fonts:
        - asset: fonts/Digit/Digit.ttf
          weight: 500
    - family: Advanced_Led_Board-7
      fonts:
        - asset: fonts/Advanced_Led_Board-7/Advanced_Led_Board-7.ttf
          weight: 500
    - family: Arcade
      fonts:
        - asset: fonts/Arcade/Arcade.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
