name: cashcard
description: An internal card based payment solution for kiosks.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Flutter 3.3.9
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.4+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_icons: ^1.1.0
  mysql1: ^0.20.0
  path: ^1.8.2
  # flushbar: 1.9.1
  another_flushbar: ^1.12.29
  # virtual_keyboard: 0.1.4
  virtual_keyboard_2: ^0.0.2
  # libserialport: ^0.3.0+1
  flutter_libserialport: ^0.3.0
  # ffi_libserialport:
  #   git:
  #     url: https://github.com/defned/ffi_libserialport.git
  #     ref: 40c358b09bca080f6d69d0f7bc50e242b7f1192d
  #   # path: ../ffi_libserialport
  auto_size_text: ^3.0.0
  fluro: any
  logging: any
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # - blobs/libserialport_c-mac64.so
    # - blobs/libserialport_c-win64.dll
    - lang/hu.json
    - lang/en.json

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Digit
      fonts:
        - asset: fonts/Digit/Digit.ttf
          weight: 500
    - family: Advanced_Led_Board-7
      fonts:
        - asset: fonts/Advanced_Led_Board-7/Advanced_Led_Board-7.ttf
          weight: 500
    - family: Arcade
      fonts:
        - asset: fonts/Arcade/Arcade.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
